### ISSUE TITLE
Error detected while processing function VimErlangTags

### ISSUE THREAD

**Issue by halturin** [vim-erlang/vim-erlang-tags#40]
Ive got this error on ErlangTags command

```
vim-erlang-tag failed with: escript: exception error: "Some process takes to long"^@  in function  vim_erlang_tags_erl__escript__1598__5
38296__489312__4:'-create_tags/1-fun-0-'/1 (/home/taras/.vim/plugged/vim-erlang-tags/plugin/../bin/vim_erlang_tags.erl, line 292)^@  in
call from lists:foreach/2 (lists.erl, line 1338)^@  in call from vim_erlang_tags_erl__escript__1598__538296__489312__4:create_tags/1 (/h
ome/taras/.vim/plugged/vim-erlang-tags/plugin/../bin/vim_erlang_tags.erl, line 288)^@  in call from vim_erlang_tags_erl__escript__1598__
538296__489312__4:run/1 (/home/taras/.vim/plugged/vim-erlang-tags/plugin/../bin/vim_erlang_tags.erl, line 139)^@  in call from escript:r
un/2 (escript.erl, line 758)^@  in call from escript:start/1 (escript.erl, line 277)^@  in call from init:start_em/1 ^@  in call from in
it:do_boot/3 ^@
```

is there any way to fix it? am i doing something wrong?

PS:
Debian 10

**Comment by hcs42** [comment]
Hi,

- Is the current working directory your project directory when you call this command?
- Do you get the same result if you execute `/home/taras/.vim/plugged/vim-erlang-tags/plugin/../bin/vim_erlang_tags.erl` from the shell? (From the same directory?)
- Is your project large? Do you get the same result if you execute the command only with a few Erlang files?
- Could you execute `vim_erlang_tags.erl -v` to print a verbose output and attach the result?
- Could you modify the timeout in line 292 from "5000" (5 seconds) to e.g. "60000" (one minute) and check what happens?

**Comment by halturin** [comment]
Hi, thanks for getting back.

Here is the result on my side.

1. yes
2. yes, the same directory, the same result
3. no, pretty small (https://github.com/halturin/mx)
4. attached
[output.log.gz](https://github.com/vim-erlang/vim-erlang-tags/files/5178002/output.log.gz)
5. changed the timeout to 60000 and got memory leak. just killed by ctrl-C
![image](https://user-images.githubusercontent.com/118860/92304281-cea31980-ef7c-11ea-8153-a93ca3f03a2f.png)

**Comment by hcs42** [comment]
According to output.log.gz, the current directory contains more than 16000 Erlang source files, which is too much to be indexed. You probably don't actually want to run vim-erlang-tags on all of these files. My suggestion is to run vim-erlang-tags from the command line and specifying the directories that contain the source files you actually want to index. E.g.:

    $ ../bin/vim_erlang_tags.erl src

or

    $ ../bin/vim_erlang_tags.erl src deps

**Comment by halturin** [comment]
not sure about 16K files. 
`find . -type f -name "*.erl" | wc -l` 
shows only 177 including vendored dependencies 
![image](https://user-images.githubusercontent.com/118860/93019996-fc223f80-f5da-11ea-8378-b02ff1bfc495.png)

**Comment by hcs42** [comment]
Hm, that's interesting...

The `output.log` file that you sent starts with the following:

```
In create_tags, To explore: ["_build/default/lib/goldrush/src/glc.erl",
                            ...16358 files...
                             "test/mx_tests.erl"]
```

Then it contains log entries about starting to process all those files.

Are those 16k Erlang source files that are in `output.log` not actually there in your file system?

**Comment by halturin** [comment]
i found the reason. there is a symlink to itself in `rel` directory
![image](https://user-images.githubusercontent.com/118860/93026761-a3699b80-f608-11ea-92b5-d9bb935f541d.png)
its just a recursion.

**Comment by hcs42** [comment]
@halturin Would you test [my modification](https://github.com/hcs42/vim-erlang-tags/commits/symlinks) that doesn't follow symbolic links by default?

**Comment by halturin** [comment]
dont you think it would be better to have some set of directories that should be ignoring?

PS: is there any chance to have an index for the OTP library within the project' dir? as it has been done in vscode

**Comment by hcs42** [comment]
> dont you think it would be better to have some set of directories that should be ignored?

You can set directories to be ignored. If you use the `vim_erlang_tags.erl` script, you can use the [`--ignore` option](https://github.com/vim-erlang/vim-erlang-tags/blob/e4bfe17793956f28846b7969f4620dbb168bd044/bin/vim_erlang_tags.erl#L524). If you use the `:ErlangTags` command, you can do this with the [erlang_tags_ignore](https://github.com/vim-erlang/vim-erlang-tags#gerlang_tags_ignore) variable.

Adding a set of default directories to ignore would not be trivial, because that depends on which build system is used by the user (rebar2? rebar3? Erlang.mk? Custom makefiles? Nothing?), and even on the users preference (some people might want to generate the tags for the dependencies in `_build`, while other don't). I think it's better to keep `vim-erlang-tags` as a simple tool that everyone can use in their preferred way.

> PS: is there any chance to have an index for the OTP library within the project' dir? as it has been done in vscode

Just like you can create tags for your own project, you can create an index for the Erlang/OTP source code. I suggest using the `vim_erlang_tags.erl` script for that, and updating your vimrc to add the new tag file to its list of tag files:

```
set tags+=/path/to/tags
```

I'm not familiar with how VS Code handles Erlang tags. In any case, deciding where to find the source files in outside the scope of this project. Regarding the concrete example, we don't know whether a user has Erlang source on their machine at all. They might have the Erlang source code multiple times. Deciding when to generate source file is also outside the scope of this project.

**Comment by hcs42** [comment]
I pushed the symlink fix into master.

**Comment by halturin** [comment]
I think we can close this issue. dont you mind?

**Comment by hcs42** [comment]
Yes, I think so.
